[package]
name = "modal-cli-net"
version = "0.1.0"
edition = "2021"
description = "Network commands for Modal CLI"
license = "MIT"
repository = "https://github.com/modality-org/modality"
homepage = "https://www.modality.org"

[dependencies]
modal-cli-common = { path = "../modal-cli-common", version = "0.1.0" }
modal-networks = { path = "../modal-networks", version = "0.1.0" }
anyhow = "1.0"
clap = { version = "4.1.11", features = ["derive"] }
