[package]
name = "modal"
version = "0.1.0"
edition = "2021"
description = "Alias for the modality CLI"
license = "MIT"
documentation = "https://docs.rs/modal"
repository = "https://github.com/modality-org/modality"
homepage = "https://www.modality.org"
readme = "../README.md"

[features]
default = ["full"]
contract-onboarding = ["modality/contract-onboarding"]
full = ["modality/full"]

[dependencies]
modality = { path = "../modality", version = "0.1.7", default-features = false }
