import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'for-agents',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/index',
        'getting-started/installation',
        'getting-started/first-contract',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'concepts/index',
        'concepts/models-vs-rules',
        'concepts/append-only-logs',
        'concepts/hash-commitments',
        'concepts/mod-contract',
        'concepts/state-machines',
        'concepts/modal-logic',
        'concepts/predicates',
        'concepts/potentialism',
        'concepts/modality-ids',
      ],
    },
    {
      type: 'category',
      label: 'Language Reference',
      items: [
        'language/index',
        'language/formula-cookbook',
        'language/model-cookbook',
        'language/model-syntax',
        'language/rule-syntax',
        'language/predicates',
        'language/path-types',
      ],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [
        'cli/index',
        'cli/contract-commands',
        'cli/ai-commands',
        'cli/identity-commands',
        'cli/node-commands',
        'cli/join-testnet',
        'cli/mining-testnet',
        'cli/hub-commands',
        'cli/predicate-commands',
        'cli/network-commands',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/index',
        'tutorials/rule-that-stays',
        'tutorials/states',
        'tutorials/members-only-contract',
        'tutorials/finish-stays-possible',
        'tutorials/rule-that-looks-right',
        'tutorials/whose-turn',
        'tutorials/multisig-treasury',
        'tutorials/pay-someone',
        'tutorials/too-strong-too-weak',
        'tutorials/on-the-testnet',
        'tutorials/get-paid',
        'tutorials/oracle-escrow',
        'tutorials/their-state',
        'tutorials/commit-then-show',
        'tutorials/constant-product-pool',
        'tutorials/agent-git-landing',
        'tutorials/hand-it-over',
        {
          type: 'category',
          label: 'With other people',
          items: [
            'tutorials/contract-hub',
            'tutorials/hub-and-assets',
            'tutorials/js-sdk-hub',
            'tutorials/multi-party-contract',
            'tutorials/agent-git-landing-results',
          ],
        },
      ],
    },
    'multi-agent-chess',
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/standard-predicates',
        'reference/predicate-theory',
        'reference/commit-methods',
        'reference/contract-evolution',
        'reference/verifier-rejections',
        'reference/ai-rule-suite',
        'reference/synthesis-review',
        'reference/gotchas',
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'resources/potentialist-lts',
        'rfcs/RFC-001-MODAL-CONTRACTS',
        'rfcs/RFC-002-RCID',
      ],
    },
    'faq',
  ],
};

export default sidebars;
