#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOC="$ROOT_DIR/docs/getting-started/installation.md"

required_patterns=(
  "# Installation"
  "cargo build --release -p modal --no-default-features --features contract-onboarding"
  "modal --help"
  "modality model --help"
  "Use \`modal\` for contract logs, identities, commits, status, and the first-contract"
  "Use \`modality\` for model and rule authoring tasks"
  "\`modality model synthesize\`"
  "\`modality model validate\`"
  "\`modality model lint\`"
  "A successful onboarding install should make both command surfaces visible"
  "Git URL installs are measured by"
  "tests/cli/check-modal-git-install-readiness.sh"
  "installs \`modal\` into a"
  "temporary Cargo root"
  "runs the"
  "first-contract CLI smoke when a built \`modality\` binary is supplied"
  "MODAL_ONBOARDING_GIT_REV=<commit>"
  "pin the exact Git revision"
  "Release-archive-shaped binary bundles are measured by"
  "tests/cli/check-modal-release-archive-readiness.sh"
  "modal-<version>-<os>-<arch>-<profile>.tar.gz"
  "containing \`bin/modal\` and"
  "\`README.txt\`"
  "plus \`PROVENANCE.txt\`, \`EVIDENCE-BUNDLE.txt\`, and \`SHA256SUMS\`"
  "unpacks it"
  "verifies the"
  "checksum manifest"
  "archive contains"
  "exactly those five entries"
  "manifest covers exactly \`bin/modal\`"
  "\`README.txt\`, and"
  "\`PROVENANCE.txt\` plus \`EVIDENCE-BUNDLE.txt\`"
  "The provenance file records the"
  "source revision, version,"
  "profile, features, platform, and expected help"
  "surface"
  "evidence manifest names the replayable evidence bundle"
  "artifact,"
  "source revision,"
  "binary,"
  "provenance file,"
  "checksum file,"
  "post-unpack checks"
  "It checks the unpacked"
  "help surface"
  "MODAL_ONBOARDING_ARCHIVE_EXPECT_REV=<commit>"
  "when release evidence must fail"
  "if the built \`modal\` binary is stale"
  ".github/workflows/onboarding-release-archive.yml"
  "GitHub Actions without publishing anything"
  "builds \`modality\`"
  "builds the"
  "lean release \`modal\` wrapper"
  "contract-onboarding"
  "uploads the verified"
  "detached tarball checksum"
  "VERIFY-DOWNLOAD.txt"
  "verification recipe"
  "workflow artifact"
  "recipe names, in order, the artifact, exact downloaded directory entries,"
  "expected source revision, expected help surface, and verifier command"
  "summary prints the exact"
  "gh run download"
  "matching \`MODAL_ONBOARDING_ARTIFACT_EXPECT_REV=<commit>\` replay verifier"
  "workflow_dispatch"
  "modal-v*"
  "After downloading that artifact"
  "verify it before unpacking"
  "tests/cli/check-modal-release-artifact-download.sh"
  "/path/to/downloaded-artifact-dir"
  "expects exactly one \`modal-*.tar.gz\`"
  "matching"
  ".sha256"
  "plus exactly one \`VERIFY-DOWNLOAD.txt\` recipe"
  "rejects any"
  "other top-level entries"
  "regular non-symlink files"
  "canonical \`0644\` modes"
  "the detached checksum first"
  "detached checksum sidecar to be one canonical SHA-256 line"
  "naming"
  "exactly that one archive"
  "internal checksum"
  "manifest entries in the emitted order"
  "executable \`bin/modal\`"
  "regular non-symlink unpacked files"
  "expected payload modes"
  "\`bin/modal\` as"
  "\`0755\`"
  "text and checksum files as"
  "\`0644\`"
  "provenance metadata, source revision,"
  "single provenance marker"
  "provenance file must keep exactly one value for version"
  "profile, features,"
  "help surface, OS, and architecture"
  "OS and architecture values must stay"
  "archive-safe lowercase platform tokens"
  "profile must be one of the"
  "supported build profiles"
  "\`debug\` or \`release\`"
  "feature set must be one of the"
  "supported wrapper feature sets"
  "\`contract-onboarding\` or \`full\`"
  "stale, partial, or"
  "unsupported provenance fails"
  "provenance marker must also appear exactly once"
  "hand-merged provenance"
  "preambles fail"
  "embedded revision marker"
  "must match the single source revision"
  "stale version metadata still fails"
  "help surface recorded in provenance must also be one of the supported"
  "surfaces"
  "\`lean\` or \`full\`"
  "optional smoke replay checks that the unpacked"
  "binary reports the exact version named by provenance"
  "before checking that exact"
  "help surface instead of assuming a default"
  "A consistently edited README,"
  "provenance file, and recipe that invent a new surface"
  "README must keep the artifact marker"
  "repeat the same version, profile,"
  "and help surface as provenance"
  "stale human-facing bundle notes fail"
  "README metadata fields must also be single-valued"
  "hand-edited notes with both current and stale values fail"
  "provenance file must name exactly one source revision"
  "ambiguous or"
  "hand-merged provenance fails"
  "evidence bundle must also keep naming"
  "checked binary, provenance file,"
  "checksum manifest,"
  "post-unpack smoke checks"
  "cannot omit the replay ingredients"
  "Those evidence"
  "manifest fields must also be single-valued"
  "hand-merged manifests with both"
  "current and stale replay ingredients fail"
  "recipe's"
  "archive, checksum, revision, and verifier command"
  "archive filename must match the version"
  "OS, architecture, and profile"
  "recorded in provenance"
  "consistently renamed tarball"
  "sidecar, and recipe"
  "fails before the binary is trusted"
  "recipe's artifact section must name exactly the one downloaded archive"
  "stale or hand-edited extra artifact names fail before unpacking"
  "recipe title must also appear exactly once"
  "hand-merged recipe preambles"
  "recipe names exactly the expected downloaded directory"
  "entries in the emitted order"
  "the archive, its"
  ".sha256"
  "sidecar, and"
  "VERIFY-DOWNLOAD.txt"
  "recipe's expected source revision section must name exactly the same single"
  "revision as the unpacked provenance"
  "recipe's expected help surface section must name exactly the same single"
  "help surface as the unpacked provenance"
  "stale lean-versus-full replay"
  "recipe fails before the binary is trusted"
  "Those recipe sections must stay in the emitted order"
  "hand-shuffled recipe"
  "fails even when each section still carries the expected value"
  "MODAL_ONBOARDING_ARTIFACT_EXPECT_REV=<commit>"
  "unless its internal provenance matches one exact source revision"
  "uploaded \`VERIFY-DOWNLOAD.txt\` repeats the expected source revision"
  "exact verifier command"
  "MODAL_ONBOARDING_ARTIFACT_SMOKE=1"
  "MODALITY_BIN=/path/to/modality"
  "replay environment"
  "detached checksum command"
  "smoke replay description"
  "must each appear exactly once"
  "stale duplicate replay"
  "commands fail before the binary is trusted"
  "replay note must remain the exact final two-line trailer"
  "stale inserted"
  "split the optional smoke instructions"
  "External crates.io-style packaging is tracked separately"
  "tests/cli/check-modal-package-readiness.sh"
  "workspace CLI crates that \`modal\` depends on are available from the"
  "registry"
  "selected direct workspace dependencies"
  "\`modal-cli-contract\`, \`modal-common\`, and \`modality\`"
  "selected package"
  "\`modal-cli-common\`, \`modal-cli-contract\`, \`modal-common\`, \`modality\`"
  "and \`modality-lang\`"
  "For the language CLI, \`modality --help\` should only expose the model command"
  "group, and \`modality model --help\` should expose the parser and review tools"
  "check      Check a formula against a model"
  "synthesize Synthesize a model from a template"
  "validate   Validate a contract model"
  "lint       Lint governance formulas"
  "You should not see the full runtime command groups"
  "hub"
  "node"
  "predicate"
  "program"
  "chain"
)

for pattern in "${required_patterns[@]}"; do
  if ! grep -Fq -- "$pattern" "$DOC"; then
    echo "installation guide is missing onboarding CLI split text: $pattern" >&2
    exit 1
  fi
done

if grep -Eq -- '(^|[^[:alnum:]_])(->|implies)([^[:alnum:]_]|$)' "$DOC"; then
  echo "installation guide should avoid implication sugar" >&2
  exit 1
fi

echo "installation doc check passed"
