#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DOC="$ROOT_DIR/docs/getting-started/installation.md"
WORKFLOW="$ROOT_DIR/.github/workflows/onboarding-release-archive.yml"

required_patterns=(
  "# Installation"
  "rust/rust-toolchain.toml"
  "rustup show active-toolchain"
  "cargo metadata --locked --no-deps --format-version 1"
  "cargo build --release -p modal --no-default-features --features contract-onboarding"
  "modal --help"
  "modality model --help"
  "Use \`modal\` for contract logs, identities, commits, status, and the first-contract"
  "Use \`modality\` for model and rule authoring tasks"
  "\`modality model synthesize\`"
  "\`modality model validate\`"
  "\`modality model lint\`"
  "A successful onboarding install should make both command surfaces visible"
  "Git URL installs are measured by"
  "tests/cli/check-modal-git-install-readiness.sh"
  "installs \`modal\` into a"
  "temporary Cargo root"
  "runs the"
  "first-contract CLI smoke when a built \`modality\` binary is supplied"
  "MODAL_ONBOARDING_GIT_REV=<commit>"
  "pin the exact Git revision"
  "Release-archive-shaped binary bundles are measured by"
  "tests/cli/check-modal-release-archive-readiness.sh"
  "modal-<version>-<os>-<arch>-<profile>.tar.gz"
  "containing \`bin/modal\` and"
  "\`README.txt\`"
  "plus \`PROVENANCE.txt\`, \`EVIDENCE-BUNDLE.txt\`, and \`SHA256SUMS\`"
  "unpacks it"
  "verifies the"
  "checksum manifest"
  "archive contains"
  "exactly those five entries"
  "manifest covers exactly \`bin/modal\`"
  "\`README.txt\`, and"
  "\`PROVENANCE.txt\` plus \`EVIDENCE-BUNDLE.txt\`"
  "The provenance file records the"
  "source revision, version,"
  "profile, features, platform, and expected help"
  "surface"
  "archive producer now fails before emitting release evidence"
  "source revision is not a lowercase hex commit token"
  "unknown"
  "hand-written revision notes cannot become the advertised archive provenance"
  "evidence manifest names the replayable evidence bundle"
  "artifact,"
  "version,"
  "source revision,"
  "profile,"
  "feature set,"
  "exact help surface,"
  "binary,"
  "provenance file,"
  "checksum file,"
  "post-unpack checks"
  "It checks the unpacked"
  "help surface"
  "MODAL_ONBOARDING_ARCHIVE_EXPECT_REV=<commit>"
  "when release evidence must fail"
  "if the built \`modal\` binary is stale"
  ".github/workflows/onboarding-release-archive.yml"
  "GitHub Actions without publishing anything"
  "builds \`modality\`"
  "builds the"
  "lean release \`modal\` wrapper"
  "contract-onboarding"
  "uploads the verified"
  "detached tarball checksum"
  "VERIFY-DOWNLOAD.txt"
  "verification recipe"
  "workflow artifact"
  "recipe names, in order, the artifact, exact downloaded directory entries,"
  "expected source revision, expected profile, expected feature set,"
  "expected help surface, and verifier command"
  "summary prints the exact"
  "gh run download"
  "matching \`MODAL_ONBOARDING_ARTIFACT_EXPECT_REV=<commit>\` replay verifier"
  "summary records the GitHub artifact digest emitted by \`upload-artifact\`"
  "exact detached tarball checksum line"
  "local replay verifies"
  "platform archive identity"
  "Modality archive identity"
  "optional \`MODAL_ONBOARDING_ARTIFACT_SMOKE=1\` replay command"
  "checks the downloaded binary's version"
  "when \`MODALITY_BIN=/path/to/modality\` is available"
  "uploaded Actions artifact"
  "\`modal-linux-x86_64-release-archive-<source-revision>\` artifact name"
  "download command stays tied to the exact source revision under test"
  "summary also includes a local replay block"
  "creates an \`artifact_dir\`"
  "downloads the named artifact there"
  "runs the pinned verifier against that"
  "shows the optional smoke replay against the same directory"
  "workflow_dispatch"
  "gh workflow run \"Onboarding Release Archive\" --ref main"
  "gh run watch <run-id> --exit-status"
  "workflow summary is"
  "release-candidate handoff surface"
  "modal-v*"
  "After downloading that artifact"
  "verify it before unpacking"
  "tests/cli/check-modal-release-artifact-download.sh"
  "/path/to/downloaded-artifact-dir"
  "expects exactly one \`modal-*.tar.gz\`"
  "matching"
  ".sha256"
  "plus exactly one \`VERIFY-DOWNLOAD.txt\` recipe"
  "rejects any"
  "other top-level entries"
  "regular non-symlink files"
  "canonical \`0644\` modes"
  "the detached checksum first"
  "detached checksum sidecar to be one canonical SHA-256 line"
  "naming"
  "exactly that one archive"
  "internal checksum"
  "manifest entries in the emitted order"
  "executable \`bin/modal\`"
  "regular non-symlink unpacked files"
  "expected payload modes"
  "\`bin/modal\` as"
  "\`0755\`"
  "text and checksum files as"
  "\`0644\`"
  "provenance metadata, source revision,"
  "single provenance marker"
  "provenance file must keep exactly one value for version"
  "profile, features,"
  "help surface, OS, and architecture"
  "OS and architecture values must stay"
  "archive-safe lowercase platform tokens"
  "profile must be one of the"
  "supported build profiles"
  "\`debug\` or \`release\`"
  "feature set must be one of the"
  "supported wrapper feature sets"
  "\`contract-onboarding\` or \`full\`"
  "stale, partial, or"
  "unsupported provenance fails"
  "source revision must also be a lowercase hex commit token"
  "unknown"
  "hand-edited revision notes fail"
  "archive producer also fails before emitting release evidence"
  "OS or"
  "architecture provenance is not an archive-safe lowercase platform token"
  "unsafe platform metadata cannot be advertised"
  "build"
  "profile is not one of the supported values"
  "ad-hoc"
  "profile labels cannot become installer provenance"
  "MODAL_BIN"
  "advertised help surface or wrapper feature set is not one of the supported"
  "values, so experimental labels cannot be published as replayable installer"
  "provenance"
  "provenance marker must also appear exactly once"
  "hand-merged provenance"
  "preambles fail"
  "embedded revision marker"
  "must match the single source revision"
  "stale version metadata still fails"
  "help surface recorded in provenance must also be one of the supported"
  "surfaces"
  "\`lean\` or \`full\`"
  "optional smoke replay checks that the unpacked"
  "binary reports the exact version named by provenance"
  "before checking that exact"
  "help surface instead of assuming a default"
  "A consistently edited README,"
  "provenance file, and recipe that invent a new surface"
  "README artifact marker must appear exactly once"
  "the same version, source revision, profile,"
  "feature set, and help surface as"
  "provenance"
  "stale human-facing"
  "bundle notes fail"
  "including stale version notes"
  "Those README"
  "metadata fields"
  "must also be single-valued"
  "hand-edited notes with both"
  "current and stale"
  "provenance file must name exactly one source revision"
  "ambiguous or"
  "hand-merged provenance fails"
  "The evidence bundle marker must appear exactly once"
  "The evidence bundle must"
  "also keep naming"
  "same archive artifact"
  "version, profile, feature set, and"
  "exact help surface"
  "as provenance plus the"
  "checked binary, provenance file,"
  "checksum manifest,"
  "post-unpack smoke checks"
  "cannot omit or drift"
  "from the replay"
  "ingredients while preserving"
  "checksums"
  "Those evidence"
  "manifest"
  "fields must"
  "also be single-valued"
  "hand-merged"
  "manifests with both"
  "current and stale"
  "replay ingredients fail"
  "recipe's"
  "archive, checksum, revision, and verifier command"
  "producer smoke also mutates the downloaded archive, checksum sidecar, and"
  "recipe into directories, symlinks, or non-canonical modes"
  "top-level payload checks"
  "executable negative evidence"
  "archive filename must match the version"
  "OS, architecture, and profile"
  "recorded in provenance"
  "consistently renamed tarball"
  "sidecar, and recipe"
  "fails before the binary is trusted"
  "recipe's artifact section must name exactly the one downloaded archive"
  "missing artifact metadata"
  "stale or hand-edited extra artifact names fail before unpacking"
  "recipe title must also appear exactly once"
  "as the first line"
  "stale"
  "notes inserted before it"
  "hand-merged recipe preambles"
  "recipe names exactly the expected downloaded directory"
  "entries in the emitted order"
  "the archive, its"
  ".sha256"
  "sidecar, and"
  "VERIFY-DOWNLOAD.txt"
  "recipe's expected source revision section must name exactly the same single"
  "revision as the unpacked provenance"
  "missing revision metadata or stale"
  "duplicate revisions fail before the binary is trusted"
  "recipe's expected profile and feature-set sections must also name exactly"
  "the same single values as the unpacked provenance"
  "recipe's expected help surface section must name exactly the same single"
  "help surface as the unpacked provenance"
  "stale lean-versus-full replay"
  "recipe fails before the binary is trusted"
  "Those recipe sections must stay in the emitted order"
  "hand-shuffled recipe"
  "fails even when each section still carries the expected value"
  "MODAL_ONBOARDING_ARTIFACT_EXPECT_REV=<commit>"
  "unless its internal provenance matches one exact source revision"
  "uploaded \`VERIFY-DOWNLOAD.txt\` repeats the expected source revision"
  "exact verifier command"
  "MODAL_ONBOARDING_ARTIFACT_SMOKE=1"
  "MODALITY_BIN=/path/to/modality"
  "replay environment"
  "detached checksum command"
  "smoke replay description"
  "must each appear exactly once"
  "verification section must stay present"
  "missing, stale"
  "duplicate, or extra replay commands fail before the binary is trusted"
  "smoke replay note must remain the exact final two-line trailer"
  "inserted line cannot split the optional smoke instructions"
  "full recipe must still"
  "canonical emitted text exactly"
  "hand-inserted prose between"
  "otherwise valid sections fails before the binary is trusted"
  "External crates.io-style packaging is tracked separately"
  "tests/cli/check-modal-package-readiness.sh"
  "workspace CLI crates that \`modal\` depends on are available from the"
  "registry"
  "selected direct workspace dependencies"
  "\`modal-cli-contract\`, \`modal-common\`, and \`modality\`"
  "selected package"
  "\`modal-cli-common\`, \`modal-cli-contract\`, \`modal-common\`, \`modality\`"
  "and \`modality-lang\`"
  "For the language CLI, \`modality --help\` should only expose the model command"
  "group, and \`modality model --help\` should expose the parser and review tools"
  "check      Check a formula against a model"
  "synthesize Synthesize a model from a template"
  "validate   Validate a contract model"
  "lint       Lint governance formulas"
  "You should not see the full runtime command groups"
  "hub"
  "node"
  "predicate"
  "program"
  "chain"
)

for pattern in "${required_patterns[@]}"; do
  if ! grep -Fq -- "$pattern" "$DOC"; then
    echo "installation guide is missing onboarding CLI split text: $pattern" >&2
    exit 1
  fi
done

required_workflow_patterns=(
  "Verify pinned Rust dependency graph"
  "rustup show active-toolchain"
  "cargo metadata --locked --no-deps --format-version 1"
  "id: upload-archive"
  "name: modal-linux-x86_64-release-archive-\${{ steps.source-revision.outputs.short }}"
  "artifact_name=\"modal-linux-x86_64-release-archive-\${MODAL_SOURCE_REV}\""
  "GitHub artifact digest:"
  "steps.upload-archive.outputs.digest"
  "binary version, recorded help surface, first-contract smoke"
  "Smoke replay:"
  "### Local replay"
  "artifact_dir=/tmp/modal-release-\${MODAL_SOURCE_REV}"
  "mkdir -p \"\$artifact_dir\""
  'gh run download ${GITHUB_RUN_ID} --name ${artifact_name}'
  '--dir \"\$artifact_dir\"'
  'tests/cli/check-modal-release-artifact-download.sh \"\$artifact_dir\"'
  "Optional: replay the downloaded binary through version, help-surface, and first-contract smokes"
  "MODAL_ONBOARDING_ARTIFACT_SMOKE=1"
  "MODAL_ONBOARDING_ARTIFACT_EXPECT_REV=\${MODAL_SOURCE_REV}"
  "MODALITY_BIN=/path/to/modality"
  "tests/cli/check-modal-release-artifact-download.sh /path/to/downloaded-artifact-dir"
  "checks the unpacked binary version, recorded help surface, and first-contract path"
)

for pattern in "${required_workflow_patterns[@]}"; do
  if ! grep -Fq -- "$pattern" "$WORKFLOW"; then
    echo "onboarding release workflow summary is missing replay text: $pattern" >&2
    exit 1
  fi
done

if grep -Eq -- '(^|[^[:alnum:]_])(->|implies)([^[:alnum:]_]|$)' "$DOC"; then
  echo "installation guide should avoid implication sugar" >&2
  exit 1
fi

echo "installation doc check passed"
